In [18]:
#import
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import torch
from torch.utils.data import TensorDataset, DataLoader
from dragonnet import Dragonnet
import sys
from pathlib import Path
project_root = Path("/home/ducvu0904/Documents/Lab/RERUM")
if str(project_root) not in sys.path:
    sys.path.append(str(project_root))
sys.path.append("..")
from utils import seed_everything
from metrics import auuc, auqc, lift, krcc

In [19]:
%time train_df = pd.read_csv(r"../dataset/Hillstrom/Men/train_men.csv")
%time test_df =  pd.read_csv(r"../dataset/Hillstrom/Men/test_men.csv")
%time val_df = pd.read_csv(r"../dataset/Hillstrom/Men/val_men.csv")

CPU times: user 27.4 ms, sys: 7.04 ms, total: 34.4 ms
Wall time: 42.5 ms
CPU times: user 15.3 ms, sys: 12.1 ms, total: 27.3 ms
Wall time: 45.1 ms
CPU times: user 7.08 ms, sys: 2.01 ms, total: 9.09 ms
Wall time: 15.7 ms

In [20]:
in_features = ['recency', 'history_segment', 'history', 'mens', 'womens',
       'zip_code', 'newbie', 'channel_Multichannel', 'channel_Phone', 'channel_Web']
label_feature = ['spend']
treatment_feature = ['treatment']

In [21]:
X_train = train_df[in_features].values.astype(float) # type: ignore
y_train = train_df[label_feature].values.astype(float) # type: ignore
t_train = train_df[treatment_feature].values.astype(float) # type: ignore

X_test = test_df[in_features].values.astype(float) # type: ignore
y_test = test_df[label_feature].values.astype(float) # type: ignore
t_test = test_df[treatment_feature].values.astype(float) # type: ignore

X_val = val_df[in_features].values.astype(float) # type: ignore
y_val = val_df[label_feature].values.astype(float) # type: ignore
t_val = val_df[treatment_feature].values.astype(float) # type: ignore

In [22]:
print('X_train[:10]', X_train[:1].astype(float))

X_train[:10] [[-0.21435131  1.6331766   1.0667411   0.90252386 -1.1010233   1.07039981
   1.00043033  2.70003843 -0.88552759 -0.88616046]]

In [23]:
print('y_train[:10]', y_train[:1].astype(float))

y_train[:10] [[0.]]

In [24]:
# Transform to tensor
def to_tensor(arr):
    return torch.tensor(arr, dtype=torch.float32)

x_men_train_t = to_tensor(X_train)
x_men_val_t = to_tensor(X_val)
x_men_test_t = to_tensor(X_test)

y_men_train_t = to_tensor(y_train).reshape(-1, 1)
y_men_val_t = to_tensor(y_val).reshape(-1, 1)
y_men_test_t = to_tensor(y_test).reshape(-1, 1)

# t_train/t_val/t_test cũng tương tự
t_men_train_t = to_tensor(t_train.astype(float)).reshape(-1, 1)
t_men_val_t = to_tensor(t_val.astype(float)).reshape(-1, 1)
t_men_test_t = to_tensor(t_test.astype(float)).reshape(-1, 1)

# Data loader
train_dataset = TensorDataset(x_men_train_t, t_men_train_t, y_men_train_t)
val_dataset = TensorDataset(x_men_val_t, t_men_val_t, y_men_val_t)
test_dataset = TensorDataset(x_men_test_t, t_men_test_t, y_men_test_t)

batch_size = 6400
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, num_workers=0, pin_memory = True)
val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False, num_workers=0, pin_memory = True)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False, num_workers=0, pin_memory = True)

print("-------------------------------------------------------------")
print("✅ Completed transform to tensor ✅")
print(f"Shape of train: x={x_men_train_t.shape}; y={y_men_train_t.shape}; t={t_men_train_t.shape}")
print(f"Shape of val: x={x_men_val_t.shape}; y={y_men_val_t.shape}; t={t_men_val_t.shape}")
print(f"Shape of test: x={x_men_test_t.shape}; y={y_men_test_t.shape}; t={t_men_test_t.shape}")

-------------------------------------------------------------
✅ Completed transform to tensor ✅
Shape of train: x=torch.Size([25567, 10]); y=torch.Size([25567, 1]); t=torch.Size([25567, 1])
Shape of val: x=torch.Size([4262, 10]); y=torch.Size([4262, 1]); t=torch.Size([4262, 1])
Shape of test: x=torch.Size([12784, 10]); y=torch.Size([12784, 1]); t=torch.Size([12784, 1])

In [25]:
epochs = 150
early_stop_metric = "ema_qini"
ema = True
ema_alpha = 0.25
patience = 20
shared_hidden = 200
outcome_hidden = 100
early_stop_start = 30
print (f" epochs = {epochs}")
print (f" early stop = {early_stop_metric}")
print (f" use ema = {ema}")
print (f" ema alpha = {ema_alpha}")
print (f" patience = {patience}")
print (f" early stop start = {early_stop_start}")

 epochs = 150
 early stop = ema_qini
 use ema = True
 ema alpha = 0.25
 patience = 20
 early stop start = 30

In [26]:
import io
import optuna
from contextlib import redirect_stdout, redirect_stderr

# Minimize Optuna console noise
optuna.logging.set_verbosity(optuna.logging.WARNING)

# 1. Optuna search config (validation only)
seeds = [412312, 42, 1874, 902745, 1]
n_trials = 50
tpe_sampler_seed = 412312
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

def objective(trial):
    grid_lr = trial.suggest_float("lr", 1e-5, 3e-4, log=True)
    grid_wd = trial.suggest_float("weight_decay", 1e-5, 1e-2, log=True)
    grid_outcome_dropout = trial.suggest_float("outcome_dropout", 0.0, 0.5)
    grid_shared_dropout = trial.suggest_float("shared_dropout", 0.0, 0.5)
    grid_outcome_hidden = trial.suggest_int("outcome_hidden", 50, 400, step=50)
    grid_shared_hidden = trial.suggest_int("shared_hidden", 50, 400, step=50)
    grid_beta = trial.suggest_float("beta", 0.0, 10)
    grid_alpha = trial.suggest_float("alpha", 0.0, 10)

    val_auqc_list = []
    val_ate_err_list = []
    for SEED in seeds:
        seed_everything(SEED)

        dragonnet = Dragonnet(
            input_dim=x_men_train_t.shape[1],
            epochs=epochs,
            learning_rate=grid_lr,
            weight_decay=grid_wd,
            use_ema=ema,
            ema_alpha=ema_alpha,
            patience=patience,
            shared_hidden=grid_shared_hidden,
            outcome_hidden=grid_outcome_hidden,
            outcome_dropout=grid_outcome_dropout,
            shared_dropout=grid_shared_dropout,
            early_stop_metric=early_stop_metric,
            early_stop_start_epoch=early_stop_start,
            alpha = grid_alpha,
            beta= grid_beta
        )

        with redirect_stdout(io.StringIO()), redirect_stderr(io.StringIO()):
            dragonnet.fit(train_loader, val_loader)

        x_men_test_t_on_device = x_men_test_t.to(device)
        y0_pred, y1_pred = dragonnet.predict(x_men_test_t_on_device)

        uplift_pred = (y1_pred - y0_pred).detach().cpu().numpy().flatten()
        y_true = y_men_test_t.detach().cpu().numpy().flatten()
        t_true = t_men_test_t.detach().cpu().numpy().flatten()
        
        current_val_auqc = auqc(y_true, t_true, uplift_pred, bins=100, plot=False)
        ate_pred = uplift_pred.mean()
        ate_true = y_true[t_true == 1].mean() - y_true[t_true == 0].mean()
        current_val_ate_err = abs(ate_pred - ate_true)

        val_auqc_list.append(current_val_auqc)
        val_ate_err_list.append(current_val_ate_err)

    # Calculate aggregated metrics across the 5 validation seeds
    mean_auqc = float(np.mean(val_auqc_list))
    std_auqc = float(np.std(val_auqc_list))
    mean_ate_err = float(np.mean(val_ate_err_list))

    # Apply penalty for instability and miscalibration
    penalty_std = std_auqc * 1.0
    penalty_ate = mean_ate_err * 0.05

    final_score = mean_auqc - penalty_std - penalty_ate

    trial.set_user_attr("mean_val_auqc", mean_auqc)
    trial.set_user_attr("std_Val_auqc", std_auqc)
    trial.set_user_attr("mean_val_ate_err", mean_ate_err)
    trial.set_user_attr("final_score", final_score)
    return final_score

def print_trial_callback(study, trial):
    value = float(trial.value) if trial.value is not None else float("nan")
    best_trial = study.best_trial
    best_value = float(best_trial.value) if best_trial.value is not None else float("nan")
    print(
        f"Finished trial {trial.number}: val loss: {value:.4f} - "
        f"with hyperparameters: {trial.params} | "
        f"best trial: {best_trial.number} loss: {best_value:.4f}",
        flush=True
    )

sampler = optuna.samplers.TPESampler(seed=tpe_sampler_seed)
study = optuna.create_study(direction="maximize", sampler=sampler)
study.optimize(objective, n_trials=n_trials, show_progress_bar=True, callbacks=[print_trial_callback])

trial_rows = []
for t in study.trials:
    if t.value is None:
        continue
    trial_rows.append({
        "trial": t.number,
        "lr": round(float(t.params["lr"]), 4),
        "weight_decay": round(float(t.params["weight_decay"]), 4),
        "shared_hidden": int(t.params["shared_hidden"]),
        "outcome_hidden": int(t.params["outcome_hidden"]),
        "shared_dropout": round(float(t.params["shared_dropout"]), 3),
        "outcome_dropout": round(float(t.params["outcome_dropout"]), 3),
        "alpha": round(float(t.params["alpha"]), 3),
        "beta": round(float(t.params["beta"]), 3),
        "mean_val_auqc": float(t.value),
        "std_Val_auqc": float(t.user_attrs.get("std_Val_auqc", np.nan))
    })

df_grid = pd.DataFrame(trial_rows).sort_values("mean_val_auqc", ascending=True).reset_index(drop=True)
best_params = study.best_params
best_cfg = pd.Series({
    "lr": float(best_params["lr"]),
    "weight_decay": float(best_params["weight_decay"]),
    "shared_hidden": int(best_params["shared_hidden"]),
    "outcome_hidden": int(best_params["outcome_hidden"]),
    "shared_dropout": float(best_params["shared_dropout"]),
    "outcome_dropout": float(best_params["outcome_dropout"]),
    "alpha": float(best_params["alpha"]),
    "beta": float(best_params["beta"]),
    "mean_Val_auqc": float(study.best_value),
    "std_Val_auqc": float(study.best_trial.user_attrs.get("std_Val_auqc", np.nan))
})

  0%|          | 0/50 [00:26<?, ?it/s]

[W 2026-04-01 14:57:59,752] Trial 0 failed with parameters: {'lr': 5.070624901428979e-05, 'weight_decay': 0.00013625464993948335, 'outcome_dropout': 0.2041371296334657, 'shared_dropout': 0.2216925330468017, 'outcome_hidden': 250, 'shared_hidden': 350, 'beta': 9.347555747146833, 'alpha': 9.788862701608304} because of the following error: KeyboardInterrupt().
Traceback (most recent call last):
  File "/home/ducvu0904/miniconda3/envs/ai/lib/python3.11/site-packages/optuna/study/_optimize.py", line 206, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "/tmp/ipykernel_28308/4126071723.py", line 48, in objective
    dragonnet.fit(train_loader, val_loader)
  File "/home/ducvu0904/Documents/Lab/RERUM/dragonnet/dragonnet.py", line 80, in fit
    for x_batch , t_batch ,y_batch in train_loader:
  File "/home/ducvu0904/miniconda3/envs/ai/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 741, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/home/ducvu0904/miniconda3/envs/ai/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 801, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ducvu0904/miniconda3/envs/ai/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ducvu0904/miniconda3/envs/ai/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 54, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
            ~~~~~~~~~~~~^^^^^
  File "/home/ducvu0904/miniconda3/envs/ai/lib/python3.11/site-packages/torch/utils/data/dataset.py", line 206, in __getitem__
    return tuple(tensor[index] for tensor in self.tensors)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ducvu0904/miniconda3/envs/ai/lib/python3.11/site-packages/torch/utils/data/dataset.py", line 206, in <genexpr>
    return tuple(tensor[index] for tensor in self.tensors)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
[W 2026-04-01 14:57:59,755] Trial 0 failed with value None.

KeyboardInterrupt:

In [ ]:
from IPython.display import display

if 'study' not in globals():
    print('Run Cell 10 (Optuna tuning) first.')
else:
    print(f"Best trial: {study.best_trial.number}")
    print(f"Best mean_Val_AUQC: {study.best_value:.6f}")
    print(f"Best params: {study.best_params}")

if 'best_cfg' in globals():
    print('\nBest config table:')
    display(best_cfg.to_frame().T)
else:
    print('\nbest_cfg not found.')

if 'df_grid' in globals():
    print('\nTop 10 trials:')
    display(df_grid.head(10))
else:
    print('\ndf_grid not found.')

if 'df_results' in globals():
    print('\nPer-seed test results:')
    display(df_results)
    print('\nTest metrics mean ± std:')
    display(df_results.drop(columns='Seed').agg(['mean', 'std']))

Best trial: 40
Best mean_Val_AUQC: 0.536263
Best params: {'lr': 3.250632060616809e-05, 'weight_decay': 4.8270498289769964e-05, 'outcome_dropout': 0.29654695898615496, 'shared_dropout': 0.12267178350366371, 'outcome_hidden': 350, 'shared_hidden': 350, 'beta': 4.81328807391155, 'alpha': 9.69415290337158}

Best config table:

,lr,weight_decay,shared_hidden,outcome_hidden,shared_dropout,outcome_dropout,alpha,beta,mean_Val_auqc,std_Val_auqc
0,0.000033,0.000048,350.0,350.0,0.122672,0.296547,9.694153,4.813288,0.536263,0.012414

Top 10 trials:

,trial,lr,weight_decay,shared_hidden,outcome_hidden,shared_dropout,outcome_dropout,alpha,beta,mean_val_auqc,std_Val_auqc
0,39,0.0001,0.0000,400,250,0.031,0.262,7.245,8.514,0.249918,0.103778
1,49,0.0000,0.0001,300,300,0.028,0.003,7.811,5.668,0.271336,0.117238
2,9,0.0000,0.0001,300,350,0.161,0.181,5.129,9.998,0.279878,0.117518
3,21,0.0000,0.0004,250,250,0.109,0.390,4.740,1.134,0.281684,0.146448
4,13,0.0000,0.0000,250,200,0.360,0.340,1.864,3.201,0.298409,0.137349
5,14,0.0001,0.0000,400,300,0.137,0.486,8.951,7.591,0.313523,0.098210
6,43,0.0000,0.0001,300,400,0.064,0.299,8.403,4.822,0.321929,0.131951
7,38,0.0000,0.0001,300,400,0.058,0.282,8.462,7.018,0.342534,0.132180
8,24,0.0000,0.0037,150,350,0.019,0.438,6.116,4.392,0.348976,0.134884
9,15,0.0000,0.0014,150,300,0.314,0.425,5.741,5.385,0.349122,0.104924

In [28]:
import pandas as pd
import numpy as np
import torch

# 1. Evaluate selected config on validation and test sets (after tuning)
seeds = [412312, 42, 1874, 902745, 1]
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
all_runs = []
val_auqc_runs = []

if 'best_cfg' not in globals():
    raise ValueError("best_cfg not found. Run grid-search cell first.")

best_lr = float(best_cfg['lr'])
best_wd = float(best_cfg['weight_decay'])
best_shared_hidden = int(best_cfg['shared_hidden'])
best_outcome_hidden = int(best_cfg['outcome_hidden'])
best_shared_dropout = float(best_cfg['shared_dropout'])
best_outcome_dropout = float(best_cfg['outcome_dropout'])
best_alpha = float(best_cfg['alpha'])
best_beta = float(best_cfg['beta'])

print("Evaluating with best validation config:")
print(f"  lr={best_lr:.1e}, weight_decay={best_wd:.1e}")
print(f"  shared_hidden={best_shared_hidden}, outcome_hidden={best_outcome_hidden}")
print(f"  shared_dropout={best_shared_dropout:.3f}, outcome_dropout={best_outcome_dropout:.3f}")
print(f"  alpha={best_alpha:.3f}, beta={best_beta:.3f}")
print(f"Number of seeds: {len(seeds)}")

# 2. Loop over seeds for robust validation/test evaluation
for SEED in seeds:
    seed_everything(SEED)

    dragonnet = Dragonnet(
        input_dim=x_men_train_t.shape[1],
        epochs=epochs,
        learning_rate=best_lr,
        weight_decay=best_wd,
        use_ema=ema,
        ema_alpha=ema_alpha,
        patience=patience,
        shared_hidden=best_shared_hidden,
        outcome_hidden=best_outcome_hidden,
        outcome_dropout=best_outcome_dropout,
        shared_dropout=best_shared_dropout,
        early_stop_metric=early_stop_metric,
        early_stop_start_epoch=early_stop_start,
        alpha=best_alpha,
        beta=best_beta
    )

    dragonnet.fit(train_loader, val_loader)

    # Validation prediction for mean validation AUQC across seeds
    x_men_val_t_on_device = x_men_val_t.to(device)
    y0_val_pred, y1_val_pred = dragonnet.predict(x_men_val_t_on_device)
    uplift_val_pred = (y1_val_pred - y0_val_pred).detach().cpu().numpy().flatten()
    y_val_true = y_men_val_t.detach().cpu().numpy().flatten()
    t_val_true = t_men_val_t.detach().cpu().numpy().flatten()
    current_val_auqc = auqc(y_val_true, t_val_true, uplift_val_pred, bins=100, plot=False)
    val_auqc_runs.append(current_val_auqc)

    # Test prediction
    x_men_test_t_on_device = x_men_test_t.to(device)
    y0_pred, y1_pred = dragonnet.predict(x_men_test_t_on_device)

    uplift_pred = (y1_pred - y0_pred).detach().cpu().numpy().flatten()
    y_true = y_men_test_t.detach().cpu().numpy().flatten()
    t_true = t_men_test_t.detach().cpu().numpy().flatten()

    # ATE error
    ate_pred = uplift_pred.mean()
    ate_true = y_true[t_true == 1].mean() - y_true[t_true == 0].mean()

    all_runs.append({
        'Seed': SEED,
        'AUUC': auuc(y_true, t_true, uplift_pred, bins=100, plot=False),
        'AUQC': auqc(y_true, t_true, uplift_pred, bins=100, plot=False),
        'Lift': lift(y_true, t_true, uplift_pred, h=0.3),
        'KRCC': krcc(y_true, t_true, uplift_pred, bins=100),
        'ATE_Err': abs(ate_pred - ate_true)
    })
    print(f"  Done Seed {SEED} | Val AUQC={current_val_auqc:.4f}")

# 3. Aggregate validation AUQC and final test metrics
avg_val_auqc = float(np.mean(val_auqc_runs))
std_val_auqc = float(np.std(val_auqc_runs))
print("\n" + "=" * 85)
print(f"Mean validation AUQC across 5 seeds: {avg_val_auqc:.4f} ± {std_val_auqc:.4f}")
print("=" * 85)

df_results = pd.DataFrame(all_runs)

print("\n" + "=" * 85)
print(f"{'PER-SEED DETAILS (TEST SET)':^85}")
print("=" * 85)
print(df_results.to_string(index=False, formatters={
    'AUUC': '{:,.4f}'.format,
    'AUQC': '{:,.4f}'.format,
    'Lift': '{:,.4f}'.format,
    'KRCC': '{:,.4f}'.format,
    'ATE_Err': '{:,.4f}'.format
}))

mean_res = df_results.drop(columns='Seed').mean()
std_res = df_results.drop(columns='Seed').std()

print("=" * 85)
print(f"{'TEST SUMMARY (MEAN ± STD)':^85}")
print("-" * 85)
for metric in ['AUUC', 'AUQC', 'Lift', 'KRCC', 'ATE_Err']:
    print(f"{metric:<10}: {mean_res[metric]:.4f} ± {std_res[metric]:.4f}")
print("=" * 85)

Evaluating with best validation config:
  lr=3.3e-05, weight_decay=4.8e-05
  shared_hidden=350, outcome_hidden=350
  shared_dropout=0.123, outcome_dropout=0.297
  alpha=9.694, beta=4.813
Number of seeds: 5
🔃🔃🔃Begin training Dragonnet🔃🔃🔃
📊 Early Stop Metric: EMA_QINI
📊 Early Stop Start Epoch: 31
📊 Strategy: Best EMA Qini (alpha=0.25)
   Restore to epoch with highest smoothed (EMA) Qini score
   Patience: 20 epochs
Epoch 1/150 | Base Loss: 257.3862 | Tarreg Loss: 608.389404 | Total Loss: 865.7756 | Val Loss: 505.4324 | Val Qini: 0.5406 | EMA Qini: 0.5406 | Best EMA: 0.5406 ⭐ NEW BEST EMA
Epoch 2/150 | Base Loss: 424.5822 | Tarreg Loss: 1009.060852 | Total Loss: 1433.6431 | Val Loss: 505.3989 | Val Qini: 0.6399 | EMA Qini: 0.5654 | Best EMA: 0.5654 ⭐ NEW BEST EMA
Epoch 3/150 | Base Loss: 402.5339 | Tarreg Loss: 954.271912 | Total Loss: 1356.8058 | Val Loss: 505.3650 | Val Qini: 0.6891 | EMA Qini: 0.5964 | Best EMA: 0.5964 ⭐ NEW BEST EMA
Epoch 4/150 | Base Loss: 343.2242 | Tarreg Loss: 816.246033 | Total Loss: 1159.4702 | Val Loss: 505.3304 | Val Qini: 0.7139 | EMA Qini: 0.6258 | Best EMA: 0.6258 ⭐ NEW BEST EMA
Epoch 5/150 | Base Loss: 322.7564 | Tarreg Loss: 762.836853 | Total Loss: 1085.5933 | Val Loss: 505.2948 | Val Qini: 0.7300 | EMA Qini: 0.6518 | Best EMA: 0.6518 ⭐ NEW BEST EMA
Epoch 6/150 | Base Loss: 588.2945 | Tarreg Loss: 1405.188232 | Total Loss: 1993.4827 | Val Loss: 505.2573 | Val Qini: 0.7204 | EMA Qini: 0.6690 | Best EMA: 0.6690 ⭐ NEW BEST EMA
Epoch 7/150 | Base Loss: 321.7463 | Tarreg Loss: 765.843933 | Total Loss: 1087.5903 | Val Loss: 505.2169 | Val Qini: 0.7120 | EMA Qini: 0.6797 | Best EMA: 0.6797 ⭐ NEW BEST EMA
Epoch 8/150 | Base Loss: 589.5479 | Tarreg Loss: 1409.457397 | Total Loss: 1999.0054 | Val Loss: 505.1725 | Val Qini: 0.7047 | EMA Qini: 0.6860 | Best EMA: 0.6860 ⭐ NEW BEST EMA
Epoch 9/150 | Base Loss: 367.7843 | Tarreg Loss: 871.819397 | Total Loss: 1239.6038 | Val Loss: 505.1230 | Val Qini: 0.7067 | EMA Qini: 0.6912 | Best EMA: 0.6912 ⭐ NEW BEST EMA
Epoch 10/150 | Base Loss: 715.0578 | Tarreg Loss: 1697.947388 | Total Loss: 2413.0051 | Val Loss: 505.0653 | Val Qini: 0.7192 | EMA Qini: 0.6982 | Best EMA: 0.6982 ⭐ NEW BEST EMA
Epoch 11/150 | Base Loss: 548.7059 | Tarreg Loss: 1316.189941 | Total Loss: 1864.8958 | Val Loss: 504.9996 | Val Qini: 0.7233 | EMA Qini: 0.7045 | Best EMA: 0.7045 ⭐ NEW BEST EMA
Epoch 12/150 | Base Loss: 443.9287 | Tarreg Loss: 1055.496704 | Total Loss: 1499.4254 | Val Loss: 504.9246 | Val Qini: 0.7154 | EMA Qini: 0.7072 | Best EMA: 0.7072 ⭐ NEW BEST EMA
Epoch 13/150 | Base Loss: 438.1887 | Tarreg Loss: 1037.809570 | Total Loss: 1475.9983 | Val Loss: 504.8374 | Val Qini: 0.7121 | EMA Qini: 0.7084 | Best EMA: 0.7084 ⭐ NEW BEST EMA
Epoch 14/150 | Base Loss: 474.7880 | Tarreg Loss: 1127.193115 | Total Loss: 1601.9812 | Val Loss: 504.7383 | Val Qini: 0.7104 | EMA Qini: 0.7089 | Best EMA: 0.7089 ⭐ NEW BEST EMA
Epoch 15/150 | Base Loss: 544.9921 | Tarreg Loss: 1295.849121 | Total Loss: 1840.8413 | Val Loss: 504.6246 | Val Qini: 0.7108 | EMA Qini: 0.7094 | Best EMA: 0.7094 ⭐ NEW BEST EMA
Epoch 16/150 | Base Loss: 456.5297 | Tarreg Loss: 1076.685303 | Total Loss: 1533.2150 | Val Loss: 504.4930 | Val Qini: 0.7048 | EMA Qini: 0.7083 | Best EMA: 0.7094 (patience: 0/20)
Epoch 17/150 | Base Loss: 699.7194 | Tarreg Loss: 1676.828979 | Total Loss: 2376.5483 | Val Loss: 504.3414 | Val Qini: 0.7054 | EMA Qini: 0.7075 | Best EMA: 0.7094 (patience: 0/20)
Epoch 18/150 | Base Loss: 334.6577 | Tarreg Loss: 790.417419 | Total Loss: 1125.0752 | Val Loss: 504.1729 | Val Qini: 0.7073 | EMA Qini: 0.7075 | Best EMA: 0.7094 (patience: 0/20)
Epoch 19/150 | Base Loss: 527.8917 | Tarreg Loss: 1250.811890 | Total Loss: 1778.7036 | Val Loss: 503.9907 | Val Qini: 0.7084 | EMA Qini: 0.7077 | Best EMA: 0.7094 (patience: 0/20)
Epoch 20/150 | Base Loss: 317.8696 | Tarreg Loss: 748.086304 | Total Loss: 1065.9559 | Val Loss: 503.7953 | Val Qini: 0.7111 | EMA Qini: 0.7086 | Best EMA: 0.7094 (patience: 0/20)
Epoch 21/150 | Base Loss: 440.0159 | Tarreg Loss: 1044.901367 | Total Loss: 1484.9172 | Val Loss: 503.6001 | Val Qini: 0.7157 | EMA Qini: 0.7103 | Best EMA: 0.7103 ⭐ NEW BEST EMA
Epoch 22/150 | Base Loss: 366.5568 | Tarreg Loss: 872.265320 | Total Loss: 1238.8221 | Val Loss: 503.4084 | Val Qini: 0.7162 | EMA Qini: 0.7118 | Best EMA: 0.7118 ⭐ NEW BEST EMA
Epoch 23/150 | Base Loss: 530.0004 | Tarreg Loss: 1259.827026 | Total Loss: 1789.8274 | Val Loss: 503.2336 | Val Qini: 0.7173 | EMA Qini: 0.7132 | Best EMA: 0.7132 ⭐ NEW BEST EMA
Epoch 24/150 | Base Loss: 521.1617 | Tarreg Loss: 1237.735107 | Total Loss: 1758.8969 | Val Loss: 503.0800 | Val Qini: 0.7218 | EMA Qini: 0.7153 | Best EMA: 0.7153 ⭐ NEW BEST EMA
Epoch 25/150 | Base Loss: 413.4469 | Tarreg Loss: 978.134888 | Total Loss: 1391.5818 | Val Loss: 502.9688 | Val Qini: 0.7267 | EMA Qini: 0.7182 | Best EMA: 0.7182 ⭐ NEW BEST EMA
Epoch 26/150 | Base Loss: 453.0042 | Tarreg Loss: 1071.130371 | Total Loss: 1524.1345 | Val Loss: 502.8930 | Val Qini: 0.7294 | EMA Qini: 0.7210 | Best EMA: 0.7210 ⭐ NEW BEST EMA
Epoch 27/150 | Base Loss: 424.4520 | Tarreg Loss: 996.523987 | Total Loss: 1420.9761 | Val Loss: 502.8317 | Val Qini: 0.7324 | EMA Qini: 0.7238 | Best EMA: 0.7238 ⭐ NEW BEST EMA
Epoch 28/150 | Base Loss: 456.1582 | Tarreg Loss: 1083.135742 | Total Loss: 1539.2939 | Val Loss: 502.7821 | Val Qini: 0.7402 | EMA Qini: 0.7279 | Best EMA: 0.7279 ⭐ NEW BEST EMA
Epoch 29/150 | Base Loss: 441.2282 | Tarreg Loss: 1057.679199 | Total Loss: 1498.9075 | Val Loss: 502.7223 | Val Qini: 0.7476 | EMA Qini: 0.7329 | Best EMA: 0.7329 ⭐ NEW BEST EMA
Epoch 30/150 | Base Loss: 545.6505 | Tarreg Loss: 1294.552612 | Total Loss: 1840.2031 | Val Loss: 502.6748 | Val Qini: 0.7500 | EMA Qini: 0.7372 | Best EMA: 0.7372 ⭐ NEW BEST EMA
Epoch 31/150 | Base Loss: 208.5967 | Tarreg Loss: 484.305847 | Total Loss: 692.9026 | Val Loss: 502.6317 | Val Qini: 0.7584 | EMA Qini: 0.7425 | Best EMA: 0.7425 ⭐ NEW BEST EMA
Epoch 32/150 | Base Loss: 402.5046 | Tarreg Loss: 940.420471 | Total Loss: 1342.9250 | Val Loss: 502.5930 | Val Qini: 0.7624 | EMA Qini: 0.7474 | Best EMA: 0.7474 ⭐ NEW BEST EMA
Epoch 33/150 | Base Loss: 616.1423 | Tarreg Loss: 1464.685791 | Total Loss: 2080.8281 | Val Loss: 502.5429 | Val Qini: 0.7665 | EMA Qini: 0.7522 | Best EMA: 0.7522 ⭐ NEW BEST EMA
Epoch 34/150 | Base Loss: 371.4108 | Tarreg Loss: 877.419495 | Total Loss: 1248.8303 | Val Loss: 502.5119 | Val Qini: 0.7669 | EMA Qini: 0.7559 | Best EMA: 0.7559 ⭐ NEW BEST EMA
Epoch 35/150 | Base Loss: 494.4083 | Tarreg Loss: 1169.142334 | Total Loss: 1663.5507 | Val Loss: 502.4819 | Val Qini: 0.7706 | EMA Qini: 0.7596 | Best EMA: 0.7596 ⭐ NEW BEST EMA
Epoch 36/150 | Base Loss: 272.9813 | Tarreg Loss: 639.614380 | Total Loss: 912.5957 | Val Loss: 502.4601 | Val Qini: 0.7753 | EMA Qini: 0.7635 | Best EMA: 0.7635 ⭐ NEW BEST EMA
Epoch 37/150 | Base Loss: 661.1154 | Tarreg Loss: 1578.797607 | Total Loss: 2239.9131 | Val Loss: 502.4387 | Val Qini: 0.7782 | EMA Qini: 0.7672 | Best EMA: 0.7672 ⭐ NEW BEST EMA
Epoch 38/150 | Base Loss: 510.4449 | Tarreg Loss: 1202.315430 | Total Loss: 1712.7603 | Val Loss: 502.4280 | Val Qini: 0.7773 | EMA Qini: 0.7697 | Best EMA: 0.7697 ⭐ NEW BEST EMA
Epoch 39/150 | Base Loss: 500.7547 | Tarreg Loss: 1199.105591 | Total Loss: 1699.8604 | Val Loss: 502.4128 | Val Qini: 0.7767 | EMA Qini: 0.7715 | Best EMA: 0.7715 ⭐ NEW BEST EMA
Epoch 40/150 | Base Loss: 679.4892 | Tarreg Loss: 1612.650757 | Total Loss: 2292.1399 | Val Loss: 502.4114 | Val Qini: 0.7784 | EMA Qini: 0.7732 | Best EMA: 0.7732 ⭐ NEW BEST EMA
Epoch 41/150 | Base Loss: 464.4450 | Tarreg Loss: 1097.348389 | Total Loss: 1561.7933 | Val Loss: 502.4111 | Val Qini: 0.7818 | EMA Qini: 0.7753 | Best EMA: 0.7753 ⭐ NEW BEST EMA
Epoch 42/150 | Base Loss: 384.5932 | Tarreg Loss: 908.534180 | Total Loss: 1293.1273 | Val Loss: 502.3983 | Val Qini: 0.7803 | EMA Qini: 0.7766 | Best EMA: 0.7766 ⭐ NEW BEST EMA
Epoch 43/150 | Base Loss: 568.1046 | Tarreg Loss: 1362.109009 | Total Loss: 1930.2136 | Val Loss: 502.3795 | Val Qini: 0.7828 | EMA Qini: 0.7781 | Best EMA: 0.7781 ⭐ NEW BEST EMA
Epoch 44/150 | Base Loss: 716.2982 | Tarreg Loss: 1716.830688 | Total Loss: 2433.1289 | Val Loss: 502.3614 | Val Qini: 0.7871 | EMA Qini: 0.7804 | Best EMA: 0.7804 ⭐ NEW BEST EMA
Epoch 45/150 | Base Loss: 667.5987 | Tarreg Loss: 1591.611084 | Total Loss: 2259.2097 | Val Loss: 502.3526 | Val Qini: 0.7832 | EMA Qini: 0.7811 | Best EMA: 0.7811 ⭐ NEW BEST EMA
Epoch 46/150 | Base Loss: 405.5435 | Tarreg Loss: 963.912109 | Total Loss: 1369.4556 | Val Loss: 502.3423 | Val Qini: 0.7871 | EMA Qini: 0.7826 | Best EMA: 0.7826 ⭐ NEW BEST EMA
Epoch 47/150 | Base Loss: 354.3721 | Tarreg Loss: 842.994446 | Total Loss: 1197.3666 | Val Loss: 502.3345 | Val Qini: 0.7842 | EMA Qini: 0.7830 | Best EMA: 0.7830 ⭐ NEW BEST EMA
Epoch 48/150 | Base Loss: 538.1030 | Tarreg Loss: 1288.503418 | Total Loss: 1826.6064 | Val Loss: 502.3181 | Val Qini: 0.7849 | EMA Qini: 0.7835 | Best EMA: 0.7835 ⭐ NEW BEST EMA
Epoch 49/150 | Base Loss: 556.7073 | Tarreg Loss: 1314.527954 | Total Loss: 1871.2352 | Val Loss: 502.3069 | Val Qini: 0.7880 | EMA Qini: 0.7846 | Best EMA: 0.7846 ⭐ NEW BEST EMA
Epoch 50/150 | Base Loss: 497.0944 | Tarreg Loss: 1176.018799 | Total Loss: 1673.1133 | Val Loss: 502.2982 | Val Qini: 0.7892 | EMA Qini: 0.7858 | Best EMA: 0.7858 ⭐ NEW BEST EMA
Epoch 51/150 | Base Loss: 420.7516 | Tarreg Loss: 994.014282 | Total Loss: 1414.7659 | Val Loss: 502.2876 | Val Qini: 0.7883 | EMA Qini: 0.7864 | Best EMA: 0.7864 ⭐ NEW BEST EMA
Epoch 52/150 | Base Loss: 336.9782 | Tarreg Loss: 788.715088 | Total Loss: 1125.6934 | Val Loss: 502.2834 | Val Qini: 0.7885 | EMA Qini: 0.7869 | Best EMA: 0.7869 ⭐ NEW BEST EMA
Epoch 53/150 | Base Loss: 278.0367 | Tarreg Loss: 655.929138 | Total Loss: 933.9658 | Val Loss: 502.2772 | Val Qini: 0.7849 | EMA Qini: 0.7864 | Best EMA: 0.7869 (patience: 1/20)
Epoch 54/150 | Base Loss: 441.3133 | Tarreg Loss: 1040.929565 | Total Loss: 1482.2429 | Val Loss: 502.2704 | Val Qini: 0.7830 | EMA Qini: 0.7856 | Best EMA: 0.7869 (patience: 2/20)
Epoch 55/150 | Base Loss: 689.7336 | Tarreg Loss: 1641.998779 | Total Loss: 2331.7324 | Val Loss: 502.2641 | Val Qini: 0.7822 | EMA Qini: 0.7847 | Best EMA: 0.7869 (patience: 3/20)
Epoch 56/150 | Base Loss: 384.4261 | Tarreg Loss: 905.543640 | Total Loss: 1289.9697 | Val Loss: 502.2604 | Val Qini: 0.7835 | EMA Qini: 0.7844 | Best EMA: 0.7869 (patience: 4/20)
Epoch 57/150 | Base Loss: 319.5518 | Tarreg Loss: 748.165283 | Total Loss: 1067.7170 | Val Loss: 502.2622 | Val Qini: 0.7790 | EMA Qini: 0.7831 | Best EMA: 0.7869 (patience: 5/20)
Epoch 58/150 | Base Loss: 547.3010 | Tarreg Loss: 1294.797852 | Total Loss: 1842.0989 | Val Loss: 502.2596 | Val Qini: 0.7770 | EMA Qini: 0.7815 | Best EMA: 0.7869 (patience: 6/20)
Epoch 59/150 | Base Loss: 430.2773 | Tarreg Loss: 1037.169312 | Total Loss: 1467.4465 | Val Loss: 502.2473 | Val Qini: 0.7768 | EMA Qini: 0.7804 | Best EMA: 0.7869 (patience: 7/20)
Epoch 60/150 | Base Loss: 384.0237 | Tarreg Loss: 906.125305 | Total Loss: 1290.1490 | Val Loss: 502.2441 | Val Qini: 0.7719 | EMA Qini: 0.7782 | Best EMA: 0.7869 (patience: 8/20)
Epoch 61/150 | Base Loss: 405.6275 | Tarreg Loss: 957.270996 | Total Loss: 1362.8986 | Val Loss: 502.2438 | Val Qini: 0.7702 | EMA Qini: 0.7762 | Best EMA: 0.7869 (patience: 9/20)
Epoch 62/150 | Base Loss: 365.1115 | Tarreg Loss: 864.033997 | Total Loss: 1229.1455 | Val Loss: 502.2466 | Val Qini: 0.7698 | EMA Qini: 0.7746 | Best EMA: 0.7869 (patience: 10/20)
Epoch 63/150 | Base Loss: 522.0334 | Tarreg Loss: 1247.848145 | Total Loss: 1769.8816 | Val Loss: 502.2415 | Val Qini: 0.7701 | EMA Qini: 0.7735 | Best EMA: 0.7869 (patience: 11/20)
Epoch 64/150 | Base Loss: 499.1740 | Tarreg Loss: 1182.010986 | Total Loss: 1681.1849 | Val Loss: 502.2411 | Val Qini: 0.7655 | EMA Qini: 0.7715 | Best EMA: 0.7869 (patience: 12/20)
Epoch 65/150 | Base Loss: 442.9257 | Tarreg Loss: 1039.254517 | Total Loss: 1482.1802 | Val Loss: 502.2422 | Val Qini: 0.7639 | EMA Qini: 0.7696 | Best EMA: 0.7869 (patience: 13/20)
Epoch 66/150 | Base Loss: 329.3692 | Tarreg Loss: 774.231812 | Total Loss: 1103.6010 | Val Loss: 502.2469 | Val Qini: 0.7653 | EMA Qini: 0.7685 | Best EMA: 0.7869 (patience: 14/20)
Epoch 67/150 | Base Loss: 427.8566 | Tarreg Loss: 1013.358765 | Total Loss: 1441.2153 | Val Loss: 502.2452 | Val Qini: 0.7616 | EMA Qini: 0.7668 | Best EMA: 0.7869 (patience: 15/20)
Epoch 68/150 | Base Loss: 388.3151 | Tarreg Loss: 919.969482 | Total Loss: 1308.2845 | Val Loss: 502.2358 | Val Qini: 0.7608 | EMA Qini: 0.7653 | Best EMA: 0.7869 (patience: 16/20)
Epoch 69/150 | Base Loss: 502.0692 | Tarreg Loss: 1190.247070 | Total Loss: 1692.3162 | Val Loss: 502.2272 | Val Qini: 0.7637 | EMA Qini: 0.7649 | Best EMA: 0.7869 (patience: 17/20)
Epoch 70/150 | Base Loss: 507.9762 | Tarreg Loss: 1197.519409 | Total Loss: 1705.4956 | Val Loss: 502.2223 | Val Qini: 0.7589 | EMA Qini: 0.7634 | Best EMA: 0.7869 (patience: 18/20)
Epoch 71/150 | Base Loss: 401.7785 | Tarreg Loss: 938.537170 | Total Loss: 1340.3157 | Val Loss: 502.2168 | Val Qini: 0.7594 | EMA Qini: 0.7624 | Best EMA: 0.7869 (patience: 19/20)
Epoch 72/150 | Base Loss: 557.2322 | Tarreg Loss: 1329.316162 | Total Loss: 1886.5483 | Val Loss: 502.2150 | Val Qini: 0.7559 | EMA Qini: 0.7608 | Best EMA: 0.7869 (patience: 20/20)

🛑 Early stopping triggered at epoch 72!
   No improvement in EMA Qini for 20 epochs

✅ Training completed! Restored model to epoch 52
   Best EMA Qini: 0.7869
   Raw Qini at best EMA epoch: 0.7885
   Strategy: Selected epoch with highest smoothed (EMA) Qini
  Done Seed 412312 | Val AUQC=0.7885
🔃🔃🔃Begin training Dragonnet🔃🔃🔃
📊 Early Stop Metric: EMA_QINI
📊 Early Stop Start Epoch: 31
📊 Strategy: Best EMA Qini (alpha=0.25)
   Restore to epoch with highest smoothed (EMA) Qini score
   Patience: 20 epochs
Epoch 1/150 | Base Loss: 457.3692 | Tarreg Loss: 1173.844238 | Total Loss: 1631.2134 | Val Loss: 505.8497 | Val Qini: 0.5522 | EMA Qini: 0.5522 | Best EMA: 0.5522 ⭐ NEW BEST EMA
Epoch 2/150 | Base Loss: 537.6464 | Tarreg Loss: 1356.399292 | Total Loss: 1894.0457 | Val Loss: 505.8275 | Val Qini: 0.6369 | EMA Qini: 0.5733 | Best EMA: 0.5733 ⭐ NEW BEST EMA
Epoch 3/150 | Base Loss: 529.5814 | Tarreg Loss: 1343.215088 | Total Loss: 1872.7965 | Val Loss: 505.8086 | Val Qini: 0.6675 | EMA Qini: 0.5969 | Best EMA: 0.5969 ⭐ NEW BEST EMA
Epoch 4/150 | Base Loss: 458.0823 | Tarreg Loss: 1178.242065 | Total Loss: 1636.3245 | Val Loss: 505.7919 | Val Qini: 0.6934 | EMA Qini: 0.6210 | Best EMA: 0.6210 ⭐ NEW BEST EMA
Epoch 5/150 | Base Loss: 343.3522 | Tarreg Loss: 882.305481 | Total Loss: 1225.6577 | Val Loss: 505.7765 | Val Qini: 0.7093 | EMA Qini: 0.6431 | Best EMA: 0.6431 ⭐ NEW BEST EMA
Epoch 6/150 | Base Loss: 431.1292 | Tarreg Loss: 1096.595947 | Total Loss: 1527.7251 | Val Loss: 505.7620 | Val Qini: 0.7059 | EMA Qini: 0.6588 | Best EMA: 0.6588 ⭐ NEW BEST EMA
Epoch 7/150 | Base Loss: 530.2908 | Tarreg Loss: 1325.835571 | Total Loss: 1856.1263 | Val Loss: 505.7471 | Val Qini: 0.7011 | EMA Qini: 0.6694 | Best EMA: 0.6694 ⭐ NEW BEST EMA
Epoch 8/150 | Base Loss: 447.1646 | Tarreg Loss: 1151.763916 | Total Loss: 1598.9285 | Val Loss: 505.7305 | Val Qini: 0.7016 | EMA Qini: 0.6775 | Best EMA: 0.6775 ⭐ NEW BEST EMA
Epoch 9/150 | Base Loss: 520.6104 | Tarreg Loss: 1328.622925 | Total Loss: 1849.2334 | Val Loss: 505.7114 | Val Qini: 0.7015 | EMA Qini: 0.6835 | Best EMA: 0.6835 ⭐ NEW BEST EMA
Epoch 10/150 | Base Loss: 215.6515 | Tarreg Loss: 571.080139 | Total Loss: 786.7316 | Val Loss: 505.6889 | Val Qini: 0.6993 | EMA Qini: 0.6874 | Best EMA: 0.6874 ⭐ NEW BEST EMA
Epoch 11/150 | Base Loss: 460.5265 | Tarreg Loss: 1166.415771 | Total Loss: 1626.9423 | Val Loss: 505.6617 | Val Qini: 0.7029 | EMA Qini: 0.6913 | Best EMA: 0.6913 ⭐ NEW BEST EMA
Epoch 12/150 | Base Loss: 507.0698 | Tarreg Loss: 1269.627441 | Total Loss: 1776.6973 | Val Loss: 505.6297 | Val Qini: 0.7018 | EMA Qini: 0.6939 | Best EMA: 0.6939 ⭐ NEW BEST EMA
Epoch 13/150 | Base Loss: 598.4268 | Tarreg Loss: 1499.998657 | Total Loss: 2098.4253 | Val Loss: 505.5942 | Val Qini: 0.6987 | EMA Qini: 0.6951 | Best EMA: 0.6951 ⭐ NEW BEST EMA
Epoch 14/150 | Base Loss: 235.5102 | Tarreg Loss: 608.198486 | Total Loss: 843.7086 | Val Loss: 505.5551 | Val Qini: 0.6957 | EMA Qini: 0.6952 | Best EMA: 0.6952 ⭐ NEW BEST EMA
Epoch 15/150 | Base Loss: 567.0105 | Tarreg Loss: 1423.942261 | Total Loss: 1990.9528 | Val Loss: 505.5120 | Val Qini: 0.6971 | EMA Qini: 0.6957 | Best EMA: 0.6957 ⭐ NEW BEST EMA
Epoch 16/150 | Base Loss: 523.0510 | Tarreg Loss: 1332.659668 | Total Loss: 1855.7107 | Val Loss: 505.4670 | Val Qini: 0.6965 | EMA Qini: 0.6959 | Best EMA: 0.6959 ⭐ NEW BEST EMA
Epoch 17/150 | Base Loss: 387.4500 | Tarreg Loss: 977.007629 | Total Loss: 1364.4575 | Val Loss: 505.4237 | Val Qini: 0.6949 | EMA Qini: 0.6956 | Best EMA: 0.6959 (patience: 0/20)
Epoch 18/150 | Base Loss: 439.6375 | Tarreg Loss: 1098.460938 | Total Loss: 1538.0984 | Val Loss: 505.3900 | Val Qini: 0.6893 | EMA Qini: 0.6941 | Best EMA: 0.6959 (patience: 0/20)
Epoch 19/150 | Base Loss: 459.4930 | Tarreg Loss: 1156.685791 | Total Loss: 1616.1787 | Val Loss: 505.3754 | Val Qini: 0.6875 | EMA Qini: 0.6924 | Best EMA: 0.6959 (patience: 0/20)
Epoch 20/150 | Base Loss: 247.2256 | Tarreg Loss: 626.704529 | Total Loss: 873.9301 | Val Loss: 505.3987 | Val Qini: 0.6821 | EMA Qini: 0.6899 | Best EMA: 0.6959 (patience: 0/20)
Epoch 21/150 | Base Loss: 563.4080 | Tarreg Loss: 1394.780884 | Total Loss: 1958.1890 | Val Loss: 505.4892 | Val Qini: 0.6812 | EMA Qini: 0.6877 | Best EMA: 0.6959 (patience: 0/20)
Epoch 22/150 | Base Loss: 740.9254 | Tarreg Loss: 1804.032715 | Total Loss: 2544.9580 | Val Loss: 505.6913 | Val Qini: 0.6806 | EMA Qini: 0.6859 | Best EMA: 0.6959 (patience: 0/20)
Epoch 23/150 | Base Loss: 410.3308 | Tarreg Loss: 1010.790588 | Total Loss: 1421.1213 | Val Loss: 506.0592 | Val Qini: 0.6751 | EMA Qini: 0.6832 | Best EMA: 0.6959 (patience: 0/20)
Epoch 24/150 | Base Loss: 449.7962 | Tarreg Loss: 1087.301392 | Total Loss: 1537.0977 | Val Loss: 506.6841 | Val Qini: 0.6753 | EMA Qini: 0.6812 | Best EMA: 0.6959 (patience: 0/20)
Epoch 25/150 | Base Loss: 531.7321 | Tarreg Loss: 1283.992554 | Total Loss: 1815.7246 | Val Loss: 507.6761 | Val Qini: 0.6695 | EMA Qini: 0.6783 | Best EMA: 0.6959 (patience: 0/20)
Epoch 26/150 | Base Loss: 527.3941 | Tarreg Loss: 1267.922363 | Total Loss: 1795.3164 | Val Loss: 509.1648 | Val Qini: 0.6674 | EMA Qini: 0.6756 | Best EMA: 0.6959 (patience: 0/20)
Epoch 27/150 | Base Loss: 607.2665 | Tarreg Loss: 1438.247192 | Total Loss: 2045.5137 | Val Loss: 511.1898 | Val Qini: 0.6672 | EMA Qini: 0.6735 | Best EMA: 0.6959 (patience: 0/20)
Epoch 28/150 | Base Loss: 492.8445 | Tarreg Loss: 1145.527954 | Total Loss: 1638.3724 | Val Loss: 513.4644 | Val Qini: 0.6650 | EMA Qini: 0.6714 | Best EMA: 0.6959 (patience: 0/20)
Epoch 29/150 | Base Loss: 416.0789 | Tarreg Loss: 953.016663 | Total Loss: 1369.0956 | Val Loss: 515.6318 | Val Qini: 0.6612 | EMA Qini: 0.6688 | Best EMA: 0.6959 (patience: 0/20)
Epoch 30/150 | Base Loss: 517.6006 | Tarreg Loss: 1213.049561 | Total Loss: 1730.6501 | Val Loss: 516.6876 | Val Qini: 0.6579 | EMA Qini: 0.6661 | Best EMA: 0.6959 (patience: 0/20)
Epoch 31/150 | Base Loss: 655.4052 | Tarreg Loss: 1521.862305 | Total Loss: 2177.2676 | Val Loss: 517.0956 | Val Qini: 0.6612 | EMA Qini: 0.6649 | Best EMA: 0.6959 (patience: 1/20)
Epoch 32/150 | Base Loss: 578.9691 | Tarreg Loss: 1343.215332 | Total Loss: 1922.1844 | Val Loss: 516.3808 | Val Qini: 0.6586 | EMA Qini: 0.6633 | Best EMA: 0.6959 (patience: 2/20)
Epoch 33/150 | Base Loss: 501.6926 | Tarreg Loss: 1158.848633 | Total Loss: 1660.5413 | Val Loss: 515.3483 | Val Qini: 0.6604 | EMA Qini: 0.6626 | Best EMA: 0.6959 (patience: 3/20)
Epoch 34/150 | Base Loss: 408.3419 | Tarreg Loss: 935.262817 | Total Loss: 1343.6047 | Val Loss: 514.3260 | Val Qini: 0.6636 | EMA Qini: 0.6628 | Best EMA: 0.6959 (patience: 4/20)